In [52]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder

df = sns.load_dataset("titanic")

In [53]:
df = df.reset_index(drop=True)

In [54]:
cols = ["pclass", "sex", "age",	"sibsp", "parch", "fare", "embarked"]
x = df[cols]

- Survived : 0 = 사망, 1 = 생존
- Pclass : 1 = 1등석, 2 = 2등석, 3 = 3등석
- Sex : male = 남성, female = 여성
- Age : 나이
- SibSp : 타이타닉 호에 동승한 자매 / 배우자의 수
- Parch : 타이타닉 호에 동승한 부모 / 자식의 수
- Ticket : 티켓 번호
- Fare : 승객 요금
- Cabin : 방 호수
- Embarked : 탑승지, C = 셰르부르, Q = 퀸즈타운, S = 사우샘프턴

In [55]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   pclass    891 non-null    int64  
 1   sex       891 non-null    object 
 2   age       714 non-null    float64
 3   sibsp     891 non-null    int64  
 4   parch     891 non-null    int64  
 5   fare      891 non-null    float64
 6   embarked  889 non-null    object 
dtypes: float64(2), int64(3), object(2)
memory usage: 48.9+ KB


# 결측치(Missing Value)

## 통계치를 이용하여 결측값 채우기

In [56]:
age_median = x["age"].median()
x["age"].fillna(age_median, inplace=True)  # None값이 뜬 age를 age의 중간값으로 채워줌 

/tmp/ipykernel_771/4281657350.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x["age"].fillna(age_median, inplace=True)  # None값이 뜬 age를 age의 중간값으로 채워줌


In [57]:
x["embarked"].fillna( method='ffill', inplace=True) # 결측치를 위나 아래 값으로 채워줌 

/tmp/ipykernel_771/2608344809.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x["embarked"].fillna( method='ffill', inplace=True) # 결측치를 위나 아래 값으로 채워줌


In [58]:
x.info() # 결측치 없는 세팅

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   pclass    891 non-null    int64  
 1   sex       891 non-null    object 
 2   age       891 non-null    float64
 3   sibsp     891 non-null    int64  
 4   parch     891 non-null    int64  
 5   fare      891 non-null    float64
 6   embarked  891 non-null    object 
dtypes: float64(2), int64(3), object(2)
memory usage: 48.9+ KB


# Encoding

- 범주형 인코딩

In [59]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import numpy as np

items = ['사과', '딸기', '포도', '배', '망고', '망고', '바나나', '바나나']

In [60]:

#LabelEncoder를 객체로 생성한 후 fit()과 transform()으로 레이블 인코딩 수행
encoder = LabelEncoder() # 1. 객체 생성
encoder.fit(items) # 객체 fit encoding 대상에 대해 fit fit_transform 도 사용가능
labels = encoder.transform(items)
print('Label tranform : ', labels)       
print('Encoding Class : ', encoder.classes_)
print('Inverse Transform : ', encoder.inverse_transform([0, 1, 4, 5, 3, 3, 2, 2]))


Label tranform :  [4 0 5 3 1 1 2 2]
Encoding Class :  ['딸기' '망고' '바나나' '배' '사과' '포도']
Inverse Transform :  ['딸기' '망고' '사과' '포도' '배' '배' '바나나' '바나나']


In [61]:
#OneHotEncoder 사용
#먼저 숫자값으로 변환을 위해 LabelEncoder로 변환
print('Label encoder')
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print(labels)

Label encoder
[4 0 5 3 1 1 2 2]


In [62]:
#2차원 데이터로 변환
labels = labels.reshape(-1,1)
print(labels)

[[4]
 [0]
 [5]
 [3]
 [1]
 [1]
 [2]
 [2]]


In [63]:
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('원핫 인코딩 데이터')
print(oh_labels.toarray())
print('원핫 인코딩 데이터 차원')
print(oh_labels.shape)

원핫 인코딩 데이터
[[0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원핫 인코딩 데이터 차원
(8, 6)


- label encoding
    - 범주형 변수의 N개 종류의 값들을 0 에서 n-1 값으로 숫자를 부여하는 인코딩이다.

In [64]:
# embarked 에 label encoding 을 적용해 보자 x["embarked"] 에 적용 

In [65]:
x.head()

pclass     sex   age  sibsp  parch     fare embarked
0       3    male  22.0      1      0   7.2500        S
1       1  female  38.0      1      0  71.2833        C
2       3  female  26.0      0      0   7.9250        S
3       1  female  35.0      1      0  53.1000        S
4       3    male  35.0      0      0   8.0500        S

In [66]:
encoder = LabelEncoder()
encoder.fit(x["embarked"])
labels = encoder.transform(x["embarked"])
x["embarked"] = labels
#print('Label tranform : ', labels)       
print('Encoding Class : ', encoder.classes_)
print('Inverse Transform : ', encoder.inverse_transform([0, 1, 2, 2]))


Encoding Class :  ['C' 'Q' 'S']
Inverse Transform :  ['C' 'Q' 'S' 'S']


/tmp/ipykernel_771/1144161235.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x["embarked"] = labels


In [67]:
x.head()

pclass     sex   age  sibsp  parch     fare  embarked
0       3    male  22.0      1      0   7.2500         2
1       1  female  38.0      1      0  71.2833         0
2       3  female  26.0      0      0   7.9250         2
3       1  female  35.0      1      0  53.1000         2
4       3    male  35.0      0      0   8.0500         2

In [68]:
# sex 를 male 과 female로 변경 

In [69]:
# sex에 one hot encoding 을 적용해 보자.  x[["male","female"]] 에 적용
# del x["sex"]
# male female
#  0     1
# https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html
ohe = OneHotEncoder(sparse=False)
# ohe.fit(x[['sex']])
ohe_encoded = ohe.fit_transform(x[['sex']])
ohe_encoded_df = pd.DataFrame(ohe_encoded , columns=ohe.categories_[0])
x = pd.concat([x, ohe_encoded_df], axis =1)

/mnt/c/Users/user/Desktop/python/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py:808: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [79]:
x.head()

pclass     sex   age  sibsp  parch     fare  embarked  female  male
0       2    male  22.0      1      0   7.2500         2     0.0   1.0
1       0  female  38.0      1      0  71.2833         0     1.0   0.0
2       2  female  26.0      0      0   7.9250         2     1.0   0.0
3       0  female  35.0      1      0  53.1000         2     1.0   0.0
4       2    male  35.0      0      0   8.0500         2     0.0   1.0

- Ordinal encoding
    - 순서형 변수에 매우 적합한 인코딩 방식

In [71]:
# target encoding # 정답값에 비율을 인코딩하는 것 , 정답값을 이용해서 피쳐를 만드는거라고 보면됨 

In [72]:
x["pclass"]

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: pclass, Length: 891, dtype: int64

In [73]:
ordinal_dict = {
    1 : 0,
    2 : 1,
    3 : 2
}
x["pclass"].map(ordinal_dict)

0      2
1      0
2      2
3      0
4      2
      ..
886    1
887    0
888    2
889    0
890    2
Name: pclass, Length: 891, dtype: int64

In [74]:
x["pclass"] = x["pclass"].map(ordinal_dict)

In [75]:
x.head()

pclass     sex   age  sibsp  parch     fare  embarked  female  male
0       2    male  22.0      1      0   7.2500         2     0.0   1.0
1       0  female  38.0      1      0  71.2833         0     1.0   0.0
2       2  female  26.0      0      0   7.9250         2     1.0   0.0
3       0  female  35.0      1      0  53.1000         2     1.0   0.0
4       2    male  35.0      0      0   8.0500         2     0.0   1.0

- 정답값

In [76]:
target = df["survived"]
target.shape

(891,)

In [80]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, target)

## Feature Scaling 

In [83]:
from sklearn.linear_model import LogisticRegression

SEED = 1234
model = LogisticRegression(random_state=SEED)
model.fit(x_train,y_train)

ValueError: could not convert string to float: 'female'